# Generated by Django 5.1.2 on 2024-11-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0061_alter_receipt_id_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='the_item_cost',
        ),
    ]
