# Generated by Django 5.1.2 on 2024-11-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0062_remove_receipt_the_item_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='the_item_cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Вартість товару'),
        ),
    ]
