# Generated by Django 5.0.9 on 2024-11-02 20:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0063_receipt_the_item_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_passport_code',
            field=models.BigIntegerField(unique=True, validators=[django.core.validators.RegexValidator(code='invalid_passport', message='Номер паспорта не починається з 0 та містить 10 символів', regex='^[1-9]\\d{9}$')], verbose_name='Код паспорту'),
        ),
    ]
