# Generated by Django 5.0.9 on 2024-11-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0064_alter_customer_customer_passport_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(choices=[('1', 'XXS'), ('2', 'XS'), ('3', 'S'), ('4', 'M'), ('5', 'L'), ('6', 'XL'), ('7', 'XXL')], max_length=30, verbose_name='Розмір'),
        ),
    ]
